---
- name: import repositories.yml tasks
  import_tasks: repositories.yml

- name: import dependencies.yml tasks
  import_tasks: dependencies.yml

- name: import nix.yml tasks
  import_tasks: nix.yml
