---
collections:
  - name: community.kubernetes
    version: "2.0.1"
  - name: operator_sdk.util
    version: "0.5.0"
  - name: kubernetes.core
    version: "3.0.1"
  - name: cloud.common
    version: "3.0.0"
  - name: community.docker
    version: "3.12.1"
  - name: ansible.posix
    version: "1.5.4"
  - name: community.general
    version: "8.4.0"
  - name: ansible.windows
    version: "2.2.0"
  - name: prometheus.prometheus
    version: "0.15.1"

roles:
  - name: geerlingguy.docker
    version: "7.4.0"
